export enum tagTypes {
  user = "users",
  categories = "categories",
  product = "product",
  productSize = "productSize",
  productColor = "productColor",
  orders = "orders",
  payment = "payment",
  qa = "qa",
  tag = "tag",
  testimonial = "testimonial",
  promo = "promo",
  promotionalOffer = "promotionalOffer",
  blogs = "blogs",
}

export const tagTypesList = [
  tagTypes.user,
  tagTypes.categories,
  tagTypes.product,
  tagTypes.productSize,
  tagTypes.productColor,
  tagTypes.orders,
  tagTypes.payment,
  tagTypes.qa,
  tagTypes.tag,
  tagTypes.testimonial,
  tagTypes.promo,
  tagTypes.promotionalOffer,
];
